# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: liteclaw

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin # macOS
    goarch:
      - amd64
      - arm64
    main: ./cmd/liteclaw # 你的 main.go 路径

archives:
  - format: tar.gz
    # Windows 使用 zip
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'